[tools]

java = "openjdk-17"
"gem:bundler" = "latest"
"aqua:sharkdp/hyperfine" = "latest"
hk = "latest"
pkl = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "rust", "ruby"]

[settings.ruby]
compile = false
